### ISSUE TITLE
real time W'bal integration as info displayed

### ISSUE THREAD

**Issue by serpico** [hishizuka/pizero_bikecomputer#1]
It's more of an idea than feature request ( I'll probably never build a bike computer even given a very detailled how to like you're doing here  :-) ). 

I, nevertheless, appreciate your great work. 

I'm using using [Goldencheetah](https://github.com/GoldenCheetah/GoldenCheetah) to keep track of my bike rides and I thought it would be great for some bike tourers to have that W' bal info ( the red curve on the screenshot below ) directly available on the screen, in ( almost, recalculated every few minutes, kilometers... ) real time to, for example not overwork themselves during sorties. I didn't real dig on the what that would involve but at first glance, it seems you're already packing all what's needed on your board. 

Again it's just an idea...and congratulation 👍 on what you did.

![W'bal red graph](https://user-images.githubusercontent.com/1227077/126247465-de2b5766-596c-40d8-9009-b875288d4cce.png)

**Comment by hishizuka** [comment]
Hi, thanks for your suggestion.
It looks like it can be done with the following repository that Goldencheetah team is working on.
https://github.com/GoldenCheetah/sweatpy

**Comment by hishizuka** [comment]
Hi, @serpico, I've finally implemented it.
The input parameters are CP and W prime, and the W prime balance is updated in real time.
I' ll update the repository soon.

<img width="665" alt="スクリーンショット 2022-01-13 23 39 15" src="https://user-images.githubusercontent.com/12926652/149350673-0ae5bf65-661e-4b0b-96fc-518f29299fee.png">

**Comment by hishizuka** [comment]
Here are some screenshots.

![2022-01-22_09-20-54](https://user-images.githubusercontent.com/12926652/150660090-880b631d-f34e-401e-96e1-2fe2ced26b83.jpg)

![w_prime_balance_mini](https://user-images.githubusercontent.com/12926652/150660134-528d420f-3292-4321-aadf-de45ba94792c.png)
