### ISSUE TITLE
MIP_640 direct update

### ISSUE THREAD

**Issue by Ptosiek** [hishizuka/pizero_bikecomputer#26]
in display_core/update:

``` def update(self, buf, direct_update):
    if not self.config.G_IS_RASPI or not self.send_display:
      return

    if direct_update and self.config.G_DISPLAY in ('MIP', 'MIP_Sharp', 'MIP_Sharp_320'):
      self.display.update(buf, direct_update)
    elif self.config.G_DISPLAY in ('MIP', 'MIP_640', 'MIP_Sharp', 'MIP_Sharp_320'):
      self.display.update(buf, direct_update=False)
    elif self.config.G_DISPLAY in ('Papirus', 'DFRobot_RPi_Display'):
      self.display.update(buf)
```

MIP_640 is handled differently from the rest for direct_update. Is it a bug or is on purpose ?

**Comment by hishizuka** [comment]
Hi @Ptosiek ,
This is on purpose. To be precise, direct_update of MIP_640 is not yet implemented.
I am planning to move to MIP_640 in the future, so I will create logic optimized for this.
https://twitter.com/pi0bikecomputer/status/1436673376848728066
