### ISSUE TITLE
No issue, sorry just a question. 

### ISSUE THREAD

**Issue by ameggs** [hishizuka/pizero_bikecomputer#3]
I really like your project! it is exactly what I am looking for, I do have a couple of questions/ suggestions.  Is there a way to stream live video and the data from GPS to a mapping software. My son races and it would be cool to watch him race live through a first person camera and see his location, speed, altitude live as well.

**Comment by hishizuka** [comment]
Hi @ameggs , thank you bery much! 
It is like a live webcast system for the Tour de France. It is very difficult, but very interesting.
I don't think there is an open source solution that is just right, but it is a combination of Garmin's LiveTrack and streaming from the GoPro. There is a Youtuber who does this.
