### ISSUE TITLE
Adding GPS to the main screen.

### ISSUE THREAD

**Issue by feddie3** [hishizuka/pizero_bikecomputer#63]
Hey, I've customized the MAIN screen, but I'm not sure how to display the GPS information in a small screen on the bottom left. I'd like to replace the 'work' display with GPS. Do you have any ideas on how I can achieve this.

![image](https://github.com/hishizuka/pizero_bikecomputer/assets/94145965/74f1af4a-9ec7-421b-aeee-fa20023d6837)

**Comment by hishizuka** [comment]
Read documentation.
https://github.com/hishizuka/pizero_bikecomputer/blob/master/doc/software_installation.md#layoutyaml

GPS Items are defined in gui_config L61.
https://github.com/hishizuka/pizero_bikecomputer/blob/master/modules/gui_config.py
