### ISSUE TITLE
Can't seem to get Ride with gps working (Question)

### ISSUE THREAD

**Issue by joeydejong112** [hishizuka/pizero_bikecomputer#64]
Hi, Sorry for the many questions.

So heres what i did
1. I created a account on Ride with gps
2. I made a route on there
3. I followed your guide and got a auth_token
4. I filled in the auth_token into here:
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/48555668/9f4ede5b-cb80-482d-afa3-8e37cd658da4)
5. I started up the app and went to courses, but it is empty:
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/48555668/f3d9ad22-ac36-479b-8d79-ea2f144f8fdc)
I do have a route in RWGPS:
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/48555668/7d4745b2-492c-4a3d-a3f2-a3dfe5083df8)
6. Also when i go to upload activity i says:
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/48555668/8b93e990-3ddb-4d14-bb19-85e04dd80cc8)
7. When i do 6 the key also disapeared from the setttings.conf file

**Comment by hishizuka** [comment]
Set the value before starting the program. If the value is set during running, it will not be read.
