### ISSUE TITLE
Simple map

### ISSUE THREAD

**Issue by feddie3** [hishizuka/pizero_bikecomputer#65]
in layout.Yaml i see simple_map, but I want to put the map on one of the other screens, for example, in the MAIN. I don't know how to do it. I tried it like this, but it didn't work:
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/94145965/dea1b6e4-62a7-48bc-9077-abeae914ceb5)
Do you have any idea how I could get the map in there? Before this, you sent me the config file, but I couldn't find anything called simple_map only in layout; it was called like that.

**Comment by hishizuka** [comment]
No such functionality is available.
