### ISSUE TITLE
Download custom tiles

### ISSUE THREAD

**Issue by joeydejong112** [hishizuka/pizero_bikecomputer#67]
Hoi, i wanted to know if it was possible to predownload some tiles for example a part of a city for offline use.

Are maybe some function in the code i could use to make that possible? 

Thank you

**Comment by hishizuka** [comment]
Not available now .

Workaround:

Demo mode with course files.
https://github.com/hishizuka/pizero_bikecomputer/blob/master/doc/software_installation.md#prepare-course-files-and-maps

Also supports mbtiles created from raster tilesets, but it is a difficult procedure.
