### ISSUE TITLE
PA1010D I2C sensor

### ISSUE THREAD

**Issue by joeydejong112** [hishizuka/pizero_bikecomputer#68]
My PA1010D sensor doesnt seem to work in the pizero app, It keeps staying on a part of Japan? 
![image](https://github.com/hishizuka/pizero_bikecomputer/assets/48555668/18e7de9d-c714-46ee-9772-e87159aae202)

**Comment by hishizuka** [comment]
I do not provide support for individual modules to work.
Check to see if the library works.
https://github.com/pimoroni/pa1010d-python
