### ISSUE TITLE
Demo mode speed

### ISSUE THREAD

**Issue by joeydejong112** [hishizuka/pizero_bikecomputer#69]
Hi is it possible to make the demo speed more slower. Currently the bike is going way to fast to test certain things

**Comment by hishizuka** [comment]
I fixed it. Adjust COURSE_DIVIDE_FACTOR in modules/sensor/gps/dummy.py.
The upper limit is the number of points reduced by downsampling in the log message.

> downsampling:1838 -> **_339_**
